<?php
/**
 * Automatically generated by running "php schema.php postgresql".
 *
 * You may modify the file, but re-running schema.php against this file will
 * standardize the format without losing your schema changes. It does lose
 * any changes that are not part of schema. Use "note" field to comment on
 * schema itself, and "note" fields are not used in any code generation but
 * only staying within this file.
 *
 * @nolint
 */
///////////////////////////////////////////////////////////////////////////////
// Preamble: C++ code inserted at beginning of ext_{name}.h

DefinePreamble(<<<CPP

CPP
);

///////////////////////////////////////////////////////////////////////////////
// Constants
//
// array (
//   'name' => name of the constant
//   'type' => type of the constant
//   'note' => additional note about this constant's schema
// )

DefineConstant(
  array(
    'name'   => "PGSQL_CONNECT_FORCE_NEW",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_CONNECTION_BAD",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_CONNECTION_OK",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_SEEK_SET",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_SEEK_CUR",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_SEEK_END",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_EMPTY_QUERY",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_COMMAND_OK",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_TUPLES_OK",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_COPY_OUT",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_COPY_IN",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_BAD_RESPONSE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_NONFATAL_ERROR",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_FATAL_ERROR",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_TRANSACTION_IDLE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_TRANSACTION_ACTIVE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_TRANSACTION_INTRANS",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_TRANSACTION_INERROR",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_TRANSACTION_UNKNOWN",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_SEVERITY",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_SQLSTATE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_MESSAGE_PRIMARY",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_MESSAGE_DETAIL",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_MESSAGE_HINT",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_STATEMENT_POSITION",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_INTERNAL_POSITION",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_INTERNAL_QUERY",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_CONTEXT",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_SOURCE_FILE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_SOURCE_LINE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_DIAG_SOURCE_FUNCTION",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_ERRORS_TERSE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_ERRORS_DEFAULT",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_ERRORS_VERBOSE",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_STATUS_LONG",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_STATUS_STRING",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_CONV_IGNORE_DEFAULT",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_CONV_FORCE_NULL",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_CONV_IGNORE_DEFAULT",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_ASSOC",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_NUM",
    'type'   => Int64,
  ));

DefineConstant(
  array(
    'name'   => "PGSQL_BOTH",
    'type'   => Int64,
  ));


///////////////////////////////////////////////////////////////////////////////
// Functions
//
// array (
//   'name'   => name of the function
//   'desc'   => description of the function's purpose
//   'flags'  => attributes of the function, see base.php for possible values
//   'opt'    => optimization callback function's name for compiler
//   'note'   => additional note about this function's schema
//   'return' =>
//      array (
//        'type'  => return type, use Reference for ref return
//        'desc'  => description of the return value
//      )
//   'args'   => arguments
//      array (
//        'name'  => name of the argument
//        'type'  => type of the argument, use Reference for output parameter
//        'value' => default value of the argument
//        'desc'  => description of the argument
//      )
// )

DefineFunction(
  array(
    'name'   => "pg_affected_rows",
    'desc'   => "pg_affected_rows() returns the number of tuples (instances/records/rows) affected by INSERT, UPDATE, and DELETE queries.\n\nThis function used to be called pg_cmdtuples().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Int64,
      'desc'   => "The number of rows affected by the query. If no tuple is affected, it will return 0.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_cancel_query",
    'desc'   => "pg_cancel_query() cancels an asynchronous query sent with pg_send_query(), pg_send_query_params() or pg_send_execute(). You cannot cancel a query executed using pg_query().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_client_encoding",
    'desc'   => "PostgreSQL supports automatic character set conversion between server and client for certain character sets. pg_client_encoding() returns the client encoding as a string. The returned string will be one of the standard PostgreSQL encoding identifiers.\n\nThis function requires PHP 4.0.3 or higher and PostgreSQL 7.0 or higher. If libpq is compiled without multibyte encoding support, pg_client_encoding() always returns SQL_ASCII. Supported encoding depends on PostgreSQL version. Refer to the PostgreSQL Documentation supported encodings.\n\nThe function used to be called pg_clientencoding().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "The client encoding, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_close",
    'desc'   => "pg_close() closes the non-persistent connection to a PostgreSQL database associated with the given connection resource.\n\nUsing pg_close() is not usually necessary, as non-persistent open connections are automatically closed at the end of the script.\n\nIf there is open large object resource on the connection, do not close the connection before closing all large object resources.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_connect",
    'desc'   => "pg_connect() opens a connection to a PostgreSQL database specified by the connection_string.\n\nIf a second call is made to pg_connect() with the same connection_string as an existing connection, the existing connection will be returned unless you pass PGSQL_CONNECT_FORCE_NEW as connect_type.\n\nThe old syntax with multiple parameters \$conn = pg_connect(\"host\", \"port\", \"options\", \"tty\", \"dbname\") has been deprecated.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "PostgreSQL connection resource on success, FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection_string",
        'type'   => String,
        'desc'   => "The connection_string can be empty to use all default parameters, or it can contain one or more parameter settings separated by whitespace. Each parameter setting is in the form keyword = value. Spaces around the equal sign are optional. To write an empty value or a value containing spaces, surround it with single quotes, e.g., keyword = 'a value'. Single quotes and backslashes within the value must be escaped with a backslash, i.e., \\' and \\\\.\n\nThe currently recognized parameter keywords are: host, hostaddr, port, dbname (defaults to value of user), user, password, connect_timeout, options, tty (ignored), sslmode, requiressl (deprecated in favor of sslmode), and service. Which of these arguments exist depends on your PostgreSQL version.\n\nThe options parameter can be used to set command line parameters to be invoked by the server.",
      ),
      array(
        'name'   => "connect_type",
        'type'   => Int32,
        'value'  => "1",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_connection_busy",
    'desc'   => "pg_connection_busy() determines whether or not a connection is busy. If it is busy, a previous query is still executing. If pg_get_result() is used on the connection, it will be blocked.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE if the connection is busy, FALSE otherwise.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_connection_reset",
    'desc'   => "pg_connection_reset() resets the connection. It is useful for error recovery.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_connection_status",
    'desc'   => "pg_connection_status() returns the status of the specified connection.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "PGSQL_CONNECTION_OK or PGSQL_CONNECTION_BAD.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_convert",
    'desc'   => "pg_convert() checks and converts the values in assoc_array into suitable values for use in an SQL statement. Precondition for pg_convert() is the existence of a table table_name which has at least as many columns as assoc_array has elements. The fieldnames in table_name must match the indices in assoc_array and the corresponding datatypes must be compatible. Returns an array with the converted values on success, FALSE otherwise.\n\nIf there are boolean fields in table_name don't use the constant TRUE in assoc_array. It will be converted to the string 'TRUE' which is no valid entry for boolean fields in PostgreSQL. Use one of t, true, 1, y, yes instead. WarningThis function is EXPERIMENTAL. The behaviour of this function, its name, and surrounding documentation may change without notice in a future release of PHP. This function should be used at your own risk.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "An array of converted values, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "assoc_array",
        'type'   => String,
      ),
      array(
        'name'   => "options",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_copy_from",
    'desc'   => "pg_copy_from() inserts records into a table from rows. It issues a COPY FROM SQL command internally to insert records.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "rows",
        'type'   => String,
      ),
      array(
        'name'   => "delimiter",
        'type'   => String,
      ),
      array(
        'name'   => "null_as",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_copy_to",
    'desc'   => "pg_copy_to() copies a table to an array. It issues COPY TO SQL command internally to retrieve records.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "An array with one element for each line of COPY data. It returns FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "rows",
        'type'   => String,
      ),
      array(
        'name'   => "delimiter",
        'type'   => String,
      ),
      array(
        'name'   => "null_as",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_dbname",
    'desc'   => "pg_dbname() returns the name of the database that the given PostgreSQL connection resource.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "A string containing the name of the database the connection is to, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_delete",
    'desc'   => "pg_delete() deletes records from a table specified by the keys and values in assoc_array. If options is specified, pg_convert() is applied to assoc_array with the specified options.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE on success or FALSE on failure. Returns string if PGSQL_DML_STRING is passed via options.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "assoc_array",
        'type'   => String,
      ),
      array(
        'name'   => "options",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_end_copy",
    'desc'   => "pg_end_copy() syncs the PostgreSQL frontend (usually a web server process) with the PostgreSQL server after doing a copy operation performed by pg_put_line(). pg_end_copy() must be issued, otherwise the PostgreSQL server may get out of sync with the frontend and will report an error.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_escape_bytea",
    'desc'   => "pg_escape_bytea() escapes string for bytea datatype. It returns escaped string.\n\nWhen you SELECT a bytea type, PostgreSQL returns octal byte values prefixed with '\\' (e.g. \\032). Users are supposed to convert back to binary format manually.\n\nThis function requires PostgreSQL 7.2 or later. With PostgreSQL 7.2.0 and 7.2.1, bytea values must be cast when you enable multi-byte support. i.e. INSERT INTO test_table (image) VALUES ('\$image_escaped'::bytea); PostgreSQL 7.2.2 or later does not need a cast. The exception is when the client and backend character encoding does not match, and there may be multi-byte stream error. User must then cast to bytea to avoid this error.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A string containing the escaped data.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "data",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_escape_string",
    'desc'   => "pg_escape_string() escapes a string for insertion into the database. It returns an escaped string in the PostgreSQL format. Use of this function is recommended instead of addslashes(). If the type of the column is bytea, pg_escape_bytea() must be used instead.\n\nThis function requires PostgreSQL 7.2 or later.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A string containing the escaped data.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "data",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_execute",
    'desc'   => "Sends a request to execute a prepared statement with given parameters, and waits for the result.\n\npg_execute() is like pg_query_params(), but the command to be executed is specified by naming a previously-prepared statement, instead of giving a query string. This feature allows commands that will be used repeatedly to be parsed and planned just once, rather than each time they are executed. The statement must have been prepared previously in the current session. pg_execute() is supported only against PostgreSQL 7.4 or higher connections; it will fail when using earlier versions.\n\nThe parameters are identical to pg_query_params(), except that the name of a prepared statement is given instead of a query string.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => null,
      'desc'   => "A query result resource on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "stmtname",
        'type'   => String,
      ),
      array(
        'name'   => "params",
        'type'   => VariantVec,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_all_columns",
    'desc'   => "pg_fetch_all_columns() returns an array that contains all rows (records) in a particular column of the result resource. This function sets NULL fields to the PHP NULL value.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array with all values in the result column.\n\nFALSE is returned if column is larger than the number of columns in the result, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "column",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_all",
    'desc'   => "pg_fetch_all() returns an array that contains all rows (records) in the result resource. This function sets NULL fields to the PHP NULL value.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array with all rows in the result. Each row is an array of field values indexed by field name.\n\nFALSE is returned if there are no rows in the result, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_array",
    'desc'   => "pg_fetch_array() returns an array that corresponds to the fetched row (record).\n\npg_fetch_array() is an extended version of pg_fetch_row(). In addition to storing the data in the numeric indices (field number) to the result array, it can also store the data using associative indices (field name). It stores both indicies by default. This function sets NULL fields to the PHP NULL value.\n\npg_fetch_array() is NOT significantly slower than using pg_fetch_row(), and is significantly easier to use.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array indexed numerically (beginning with 0) or associatively (indexed by field name), or both. Each value in the array is represented as a string. Database NULL values are returned as NULL.\n\nFALSE is returned if row exceeds the number of rows in the set, there are no more rows, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "row",
        'type'   => Variant,
        'value'  => "null",
      ),
      array(
        'name'   => "result_type",
        'type'   => Int32,
        'value'  => "3",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_assoc",
    'desc'   => "pg_fetch_assoc() returns an associative array that corresponds to the fetched row (records).\n\npg_fetch_assoc() is equivalent to calling pg_fetch_array() with PGSQL_ASSOC as the optional third parameter. It only returns an associative array. If you need the numeric indices, use pg_fetch_row(). This function sets NULL fields to the PHP NULL value.\n\npg_fetch_assoc() is NOT significantly slower than using pg_fetch_row(), and is significantly easier to use.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array indexed associatively (by field name). Each value in the array is represented as a string. Database NULL values are returned as NULL.\n\nFALSE is returned if row exceeds the number of rows in the set, there are no more rows, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "row",
        'type'   => Variant,
	'value'  => 'null'
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_object",
    'desc'   => "pg_fetch_object() returns an object with properties that correspond to the fetched row's field names. It can optionally instantiate an object of a specific class, and pass parameters to that class's constructor. This function sets NULL fields to the PHP NULL value.\n\nSpeed-wise, the function is identical to pg_fetch_array(), and almost as fast as pg_fetch_row() (the difference is insignificant).",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An object with one attribute for each field name in the result. Database NULL values are returned as NULL.\n\nFALSE is returned if row exceeds the number of rows in the set, there are no more rows, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "row",
        'type'   => Variant,
        'value'  => "null",
      ),
      array(
        'name'   => "class_name",
        'type'   => String,
        'value'  => "\"stdClass\"",
      ),
      array(
        'name'   => "params",
        'type'   => VariantVec,
        'value'  => "null",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_result",
    'desc'   => "pg_fetch_result() returns the value of a particular row and field (column) in a PostgreSQL result resource.\n\nThis function used to be called pg_result().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Boolean is returned as \"t\" or \"f\". All other types, including arrays are returned as strings formatted in the same default PostgreSQL manner that you would see in the psql program. Database NULL values are returned as NULL.\n\nFALSE is returned if row exceeds the number of rows in the set, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "row",
        'type'   => Int64,
      ),
      array(
        'name'   => "field",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_fetch_row",
    'desc'   => "pg_fetch_row() fetches one row of data from the result associated with the specified result resource. This function sets NULL fields to the PHP NULL value.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array, indexed from 0 upwards, with each value represented as a string. Database NULL values are returned as NULL.\n\nFALSE is returned if row exceeds the number of rows in the set, there are no more rows, or on any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "row",
        'type'   => Variant,
        'value'  => "null",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_is_null",
    'desc'   => "pg_field_is_null() tests if a field in a PostgreSQL result resource is SQL NULL or not.\n\nThis function used to be called pg_fieldisnull().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns 1 if the field in the given row is SQL NULL, 0 if not. FALSE is returned if the row is out of range, or upon any other error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "row",
        'type'   => Int64,
      ),
      array(
        'name'   => "field",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_name",
    'desc'   => "pg_field_name() returns the name of the field occupying the given field_number in the given PostgreSQL result resource. Field numbering starts from 0.\n\nThis function used to be called pg_fieldname().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "The field name, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_number",
        'type'   => Int64,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_num",
    'desc'   => "pg_field_num() will return the number of the field number that corresponds to the field_name in the given PostgreSQL result resource.\n\nThis function used to be called pg_fieldnum().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The field number (numbered from 0), or -1 on error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_name",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_prtlen",
    'desc'   => "pg_field_prtlen() returns the actual printed length (number of characters) of a specific value in a PostgreSQL result. Row numbering starts at 0. This function will return -1 on an error.\n\nfield_name_or_number can be passed either as an integer or as a string. If it is passed as an integer, PHP recognises it as the field number, otherwise as field name.\n\nSee the example given at the pg_field_name() page.\n\nThis function used to be called pg_fieldprtlen().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The field printed length, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_name_or_number",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_size",
    'desc'   => "pg_field_size() returns the internal storage size (in bytes) of the field number in the given PostgreSQL result.\n\nThis function used to be called pg_fieldsize().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The internal field storage size (in bytes). -1 indicates a variable length field. FALSE is returned on error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_number",
        'type'   => Int64,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_table",
    'desc'   => "pg_field_table() returns the name of the table that field belongs to, or the table's oid if oid_only is TRUE.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "On success either the fields table name or oid. Or, FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_number",
        'type'   => Int64,
      ),
      array(
        'name'   => "oid_only",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_type_oid",
    'desc'   => "pg_field_type_oid() returns an integer containing the OID of the base type of the given field_number in the given PostgreSQL result resource.\n\nYou can get more information about the field type by querying PostgreSQL's pg_type system table using the OID obtained with this function. The PostgreSQL format_type() function will convert a type OID into an SQL standard type name.\n\nIf the field uses a PostgreSQL domain (rather than a basic type), it is the OID of the domain's underlying type that is returned, rather than the OID of the domain itself.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "The OID of the field's base type. FALSE is returned on error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_number",
        'type'   => Int64,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_field_type",
    'desc'   => "pg_field_type() returns a string containing the base type name of the given field_number in the given PostgreSQL result resource.\n\nIf the field uses a PostgreSQL domain (rather than a basic type), it is the name of the domain's underlying type that is returned, rather than the name of the domain itself.\n\nThis function used to be called pg_fieldtype().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the base name of the field's type, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "field_number",
        'type'   => Int64,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_free_result",
    'desc'   => "pg_free_result() frees the memory and data associated with the specified PostgreSQL query result resource.\n\nThis function need only be called if memory consumption during script execution is a problem. Otherwise, all result memory will be automatically freed when the script ends.\n\nThis function used to be called pg_freeresult().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_get_notify",
    'desc'   => "pg_get_notify() gets notifications generated by a NOTIFY SQL command. To receive notifications, the LISTEN SQL command must be issued.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array containing the NOTIFY message name and backend PID. Otherwise if no NOTIFY is waiting, then FALSE is returned.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "result_type",
        'type'   => Int32,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_get_pid",
    'desc'   => "pg_get_pid() gets the backend's (database server process) PID. The PID is useful to determine whether or not a NOTIFY message received via pg_get_notify() is sent from another process or not.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "The backend database process ID.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_get_result",
    'desc'   => "pg_get_result() gets the result resource from an asynchronous query executed by pg_send_query(), pg_send_query_params() or pg_send_execute(). pg_send_query() and the other asynchronous query functions can send multiple queries to a PostgreSQL server and pg_get_result() is used to get each query's results, one by one.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The result resource, or FALSE if no more results are available.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_host",
    'desc'   => "pg_host() returns the host name of the given PostgreSQL connection resource is connected to.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the name of the host the connection is to, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_insert",
    'desc'   => "pg_insert() inserts the values of assoc_array into the table specified by table_name. If options is specified, pg_convert() is applied to assoc_array with the specified options. WarningThis function is EXPERIMENTAL. The behaviour of this function, its name, and surrounding documentation may change without notice in a future release of PHP. This function should be used at your own risk.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure. Returns string if PGSQL_DML_STRING is passed via options.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "assoc_array",
        'type'   => String,
      ),
      array(
        'name'   => "options",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_last_error",
    'desc'   => "pg_last_error() returns the last error message for a given connection.\n\nError messages may be overwritten by internal PostgreSQL (libpq) function calls. It may not return an appropriate error message if multiple errors occur inside a PostgreSQL module function.\n\nUse pg_result_error(), pg_result_error_field(), pg_result_status() and pg_connection_status() for better error handling.\n\nThis function used to be called pg_errormessage().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the last error message on the given connection, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_last_notice",
    'desc'   => "pg_last_notice() returns the last notice message from the PostgreSQL server on the specified connection. The PostgreSQL server sends notice messages in several cases, for instance when creating a SERIAL column in a table.\n\nWith pg_last_notice(), you can avoid issuing useless queries by checking whether or not the notice is related to your transaction.\n\nNotice message tracking can be set to optional by setting 1 for pgsql.ignore_notice in php.ini.\n\nNotice message logging can be set to optional by setting 0 for pgsql.log_notice in php.ini. Unless pgsql.ignore_notice is set to 0, notice message cannot be logged.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the last notice on the given connection, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_last_oid",
    'desc'   => "pg_last_oid() is used to retrieve the OID assigned to an inserted row.\n\nOID field became an optional field from PostgreSQL 7.2 and will not be present by default in PostgreSQL 8.1. When the OID field is not present in a table, the programmer must use pg_result_status() to check for successful insertion.\n\nTo get the value of a SERIAL field in an inserted row, it is necessary to use the PostgreSQL CURRVAL function, naming the sequence whose last value is required. If the name of the sequence is unknown, the pg_get_serial_sequence PostgreSQL 8.0 function is necessary.\n\nPostgreSQL 8.1 has a function LASTVAL that returns the value of the most recently used sequence in the session. This avoids the need for naming the sequence, table or column altogether.\n\nThis function used to be called pg_getlastoid().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the OID assigned to the most recently inserted row in the specified connection, or FALSE on error or no available OID.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_close",
    'desc'   => "pg_lo_close() closes a large object. large_object is a resource for the large object from pg_lo_open().\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_loclose().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_create",
    'desc'   => "pg_lo_create() creates a large object and returns the OID of the large object. PostgreSQL access modes INV_READ, INV_WRITE, and INV_ARCHIVE are not supported, the object is created always with both read and write access. INV_ARCHIVE has been removed from PostgreSQL itself (version 6.3 and above).\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nInstead of using the large object interface (which has no access controls and is cumbersome to use), try PostgreSQL's bytea column type and pg_escape_bytea().\n\nThis function used to be called pg_locreate().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A large object OID or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "object_id",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_export",
    'desc'   => "pg_lo_export() takes a large object in a PostgreSQL database and saves its contents to a file on the local filesystem.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_loexport().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "oid",
        'type'   => String,
      ),
      array(
        'name'   => "pathname",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_import",
    'desc'   => "pg_lo_import() creates a new large object in the database using a file on the filesystem as its data source.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block. When safe mode is enabled, PHP checks whether the files or directories being operated upon have the same UID (owner) as the script that is being executed.\n\nThis function used to be called pg_loimport().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The OID of the newly created large object, or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "pathname",
        'type'   => String,
      ),
      array(
        'name'   => "object_id",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_open",
    'desc'   => "pg_lo_open() opens a large object in the database and returns large object resource so that it can be manipulated. Warning\n\nDo not close the database connection before closing the large object resource.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_loopen().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A large object resource or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "oid",
        'type'   => String,
      ),
      array(
        'name'   => "mode",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_read_all",
    'desc'   => "pg_lo_read_all() reads a large object and passes it straight through to the browser after sending all pending headers. Mainly intended for sending binary data like images or sound.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_loreadall().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Number of bytes read or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "large_object",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_read",
    'desc'   => "pg_lo_read() reads at most len bytes from a large object and returns it as a string.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_loread().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A string containing len bytes from the large object, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "large_object",
        'type'   => String,
      ),
      array(
        'name'   => "len",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_seek",
    'desc'   => "pg_lo_seek() seeks a position within a large object resource.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "large_object",
        'type'   => String,
      ),
      array(
        'name'   => "offset",
        'type'   => String,
      ),
      array(
        'name'   => "whence",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_tell",
    'desc'   => "pg_lo_tell() returns the current position (offset from the beginning) of a large object.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The current seek offset (in number of bytes) from the beginning of the large object. If there is an error, the return value is negative.",
    ),
    'args'   => array(
      array(
        'name'   => "large_object",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_unlink",
    'desc'   => "pg_lo_unlink() deletes a large object with the oid. Returns TRUE on success or FALSE on failure.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_lounlink().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "oid",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_lo_write",
    'desc'   => "pg_lo_write() writes data into a large object at the current seek position.\n\nTo use the large object interface, it is necessary to enclose it within a transaction block.\n\nThis function used to be called pg_lowrite().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The number of bytes written to the large object, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "large_object",
        'type'   => String,
      ),
      array(
        'name'   => "data",
        'type'   => String,
      ),
      array(
        'name'   => "len",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_meta_data",
    'desc'   => "pg_meta_data() returns table definition for table_name as an array. WarningThis function is EXPERIMENTAL. The behaviour of this function, its name, and surrounding documentation may change without notice in a future release of PHP. This function should be used at your own risk.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An array of the table definition, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_num_fields",
    'desc'   => "pg_num_fields() returns the number of fields (columns) in a PostgreSQL result resource.\n\nThis function used to be called pg_numfields().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The number of fields (columns) in the result. On error, -1 is returned.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_num_rows",
    'desc'   => "pg_num_rows() will return the number of rows in a PostgreSQL result resource.\n\nThis function used to be called pg_numrows().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The number of rows in the result. On error, -1 is returned.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_options",
    'desc'   => "pg_options() will return a string containing the options specified on the given PostgreSQL connection resource.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A string containing the connection options, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_parameter_status",
    'desc'   => "Looks up a current parameter setting of the server.\n\nCertain parameter values are reported by the server automatically at connection startup or whenever their values change. pg_parameter_status() can be used to interrogate these settings. It returns the current value of a parameter if known, or FALSE if the parameter is not known.\n\nParameters reported as of PostgreSQL 8.0 include server_version, server_encoding, client_encoding, is_superuser, session_authorization, DateStyle, TimeZone, and integer_datetimes. (server_encoding, TimeZone, and integer_datetimes were not reported by releases before 8.0.) Note that server_version, server_encoding and integer_datetimes cannot change after PostgreSQL startup.\n\nPostgreSQL 7.3 or lower servers do not report parameter settings, pg_parameter_status() includes logic to obtain values for server_version and client_encoding anyway. Applications are encouraged to use pg_parameter_status() rather than ad hoc code to determine these values. Caution\n\nOn a pre-7.4 PostgreSQL server, changing client_encoding via SET after connection startup will not be reflected by pg_parameter_status().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "string containing the value of the parameter, FALSE on failure or invalid param_name.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "param_name",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_pconnect",
    'desc'   => "pg_pconnect() opens a connection to a PostgreSQL database. It returns a connection resource that is needed by other PostgreSQL functions.\n\nIf a second call is made to pg_pconnect() with the same connection_string as an existing connection, the existing connection will be returned unless you pass PGSQL_CONNECT_FORCE_NEW as connect_type.\n\nTo enable persistent connection, the pgsql.allow_persistent php.ini directive must be set to \"On\" (which is the default). The maximum number of persistent connection can be defined with the pgsql.max_persistent php.ini directive (defaults to -1 for no limit). The total number of connections can be set with the pgsql.max_links php.ini directive.\n\npg_close() will not close persistent links generated by pg_pconnect().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "PostgreSQL connection resource on success, FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection_string",
        'type'   => String,
      ),
      array(
        'name'   => "host",
        'type'   => String,
      ),
      array(
        'name'   => "hostaddr",
        'type'   => String,
      ),
      array(
        'name'   => "port",
        'type'   => String,
      ),
      array(
        'name'   => "dbname",
        'type'   => String,
      ),
      array(
        'name'   => "user",
        'type'   => String,
      ),
      array(
        'name'   => "password",
        'type'   => String,
      ),
      array(
        'name'   => "connect_timeout",
        'type'   => String,
      ),
      array(
        'name'   => "options",
        'type'   => String,
      ),
      array(
        'name'   => "tty",
        'type'   => String,
      ),
      array(
        'name'   => "sslmode",
        'type'   => String,
      ),
      array(
        'name'   => "requiressl",
        'type'   => String,
      ),
      array(
        'name'   => "service",
        'type'   => String,
      ),
      array(
        'name'   => "connect_type",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_ping",
    'desc'   => "pg_ping() pings a database connection and tries to reconnect it if it is broken.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_port",
    'desc'   => "pg_port() returns the port number that the given PostgreSQL connection resource is connected to.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "An int containing the port number of the database server the connection is to, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_prepare",
    'desc'   => "pg_prepare() creates a prepared statement for later execution with pg_execute() or pg_send_execute(). This feature allows commands that will be used repeatedly to be parsed and planned just once, rather than each time they are executed. pg_prepare() is supported only against PostgreSQL 7.4 or higher connections; it will fail when using earlier versions.\n\nThe function creates a prepared statement named stmtname from the query string, which must contain a single SQL command. stmtname may be \"\" to create an unnamed statement, in which case any pre-existing unnamed statement is automatically replaced; otherwise it is an error if the statement name is already defined in the current session. If any parameters are used, they are referred to in the query as \$1, \$2, etc.\n\nPrepared statements for use with pg_prepare() can also be created by executing SQL PREPARE statements. (But pg_prepare() is more flexible since it does not require parameter types to be pre-specified.) Also, although there is no PHP function for deleting a prepared statement, the SQL DEALLOCATE statement can be used for that purpose.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A query result resource on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "stmtname",
        'type'   => String,
      ),
      array(
        'name'   => "query",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_put_line",
    'desc'   => "pg_put_line() sends a NULL-terminated string to the PostgreSQL backend server. This is needed in conjunction with PostgreSQL's COPY FROM command. COPY is a high-speed data loading interface supported by PostgreSQL. Data is passed in without being parsed, and in a single transaction.\n\nAn alternative to using raw pg_put_line() commands is to use pg_copy_from(). This is a far simpler interface.\n\nThe application must explicitly send the two characters \"\\.\" on the last line to indicate to the backend that it has finished sending its data, before issuing pg_end_copy(). Warning\n\nUse of the pg_put_line() causes most large object operations, including pg_lo_read() and pg_lo_tell(), to subsequently fail. You can use pg_copy_from() and pg_copy_to() instead.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "data",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_query_params",
    'desc'   => "Submits a command to the server and waits for the result, with the ability to pass parameters separately from the SQL command text.\n\npg_query_params() is like pg_query(), but offers additional functionality: parameter values can be specified separately from the command string proper. pg_query_params() is supported only against PostgreSQL 7.4 or higher connections; it will fail when using earlier versions.\n\nIf parameters are used, they are referred to in the query string as \$1, \$2, etc. params specifies the actual values of the parameters. A NULL value in this array means the corresponding parameter is SQL NULL.\n\nThe primary advantage of pg_query_params() over pg_query() is that parameter values may be separated from the query string, thus avoiding the need for tedious and error-prone quoting and escaping. Unlike pg_query(), pg_query_params() allows at most one SQL command in the given string. (There can be semicolons in it, but not more than one nonempty command.)",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A query result resource on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "query",
        'type'   => String,
      ),
      array(
        'name'   => "params",
        'type'   => VariantVec,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_query",
    'desc'   => "pg_query() executes the query on the specified database connection.\n\nIf an error occurs, and FALSE is returned, details of the error can be retrieved using the pg_last_error() function if the connection is valid.\n\nAlthough connection can be omitted, it is not recommended, since it can be the cause of hard to find bugs in scripts.\n\nThis function used to be called pg_exec(). pg_exec() is still available for compatibility reasons, but users are encouraged to use the newer name.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "A query result resource on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "query",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_result_error_field",
    'desc'   => "pg_result_error_field() returns one of the detailed error message fields associated with result resource. It is only available against a PostgreSQL 7.4 or above server. The error field is specified by the fieldcode.\n\nBecause pg_query() and pg_query_params() return FALSE if the query fails, you must use pg_send_query() and pg_get_result() to get the result handle.\n\nIf you need to get additional error information from failed pg_query() queries, use pg_set_error_verbosity() and pg_last_error() and then parse the result.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "string containing the contents of the error field, NULL if the field does not exist or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "fieldcode",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_result_error",
    'desc'   => "pg_result_error() returns any error message associated with the result resource. Therefore, the user has a better chance of getting the correct error message than with pg_last_error().\n\nThe function pg_result_error_field() can give much greater detail on result errors than pg_result_error().\n\nBecause pg_query() returns FALSE if the query fails, you must use pg_send_query() and pg_get_result() to get the result handle.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns a string if there is an error associated with the result parameter, FALSE otherwise.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_result_seek",
    'desc'   => "pg_result_seek() sets the internal row offset in a result resource.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "offset",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_result_status",
    'desc'   => "pg_result_status() returns the status of a result resource, or the PostgreSQL command completion tag associated with the result",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Possible return values are PGSQL_EMPTY_QUERY, PGSQL_COMMAND_OK, PGSQL_TUPLES_OK, PGSQL_COPY_OUT, PGSQL_COPY_IN, PGSQL_BAD_RESPONSE, PGSQL_NONFATAL_ERROR and PGSQL_FATAL_ERROR if PGSQL_STATUS_LONG is specified. Otherwise, a string containing the PostgreSQL command tag is returned.",
    ),
    'args'   => array(
      array(
        'name'   => "result",
        'type'   => Variant,
      ),
      array(
        'name'   => "type",
        'type'   => Int64,
	'value'  => '1'
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_select",
    'desc'   => "pg_select() selects records specified by assoc_array which has field=>value. For a successful query, it returns an array containing all records and fields that match the condition specified by assoc_array. options is specified, pg_convert() is applied to assoc_array with the specified flags. WarningThis function is EXPERIMENTAL. The behaviour of this function, its name, and surrounding documentation may change without notice in a future release of PHP. This function should be used at your own risk.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure. Returns string if PGSQL_DML_STRING is passed via options.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "assoc_array",
        'type'   => String,
      ),
      array(
        'name'   => "options",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_send_execute",
    'desc'   => "Sends a request to execute a prepared statement with given parameters, without waiting for the result(s).\n\nThis is similar to pg_send_query_params(), but the command to be executed is specified by naming a previously-prepared statement, instead of giving a query string. The function's parameters are handled identically to pg_execute(). Like pg_execute(), it will not work on pre-7.4 versions of PostgreSQL.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "TRUE on success, FALSE on failure. Use pg_get_result() to determine the query result.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "stmtname",
        'type'   => String,
      ),
      array(
        'name'   => "params",
        'type'   => VariantVec,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_send_prepare",
    'desc'   => "Sends a request to create a prepared statement with the given parameters, without waiting for completion.\n\nThis is an asynchronous version of pg_prepare(): it returns TRUE if it was able to dispatch the request, and FALSE if not. After a successful call, call pg_get_result() to determine whether the server successfully created the prepared statement. The function's parameters are handled identically to pg_prepare(). Like pg_prepare(), it will not work on pre-7.4 versions of PostgreSQL.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "TRUE on success, FALSE on failure. Use pg_get_result() to determine the query result.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "stmtname",
        'type'   => String,
      ),
      array(
        'name'   => "query",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_send_query_params",
    'desc'   => "Submits a command and separate parameters to the server without waiting for the result(s).\n\nThis is equivalent to pg_send_query() except that query parameters can be specified separately from the query string. The function's parameters are handled identically to pg_query_params(). Like pg_query_params(), it will not work on pre-7.4 PostgreSQL connections, and it allows only one command in the query string.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "TRUE on success or FALSE on failure.\n\nUse pg_get_result() to determine the query result.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "query",
        'type'   => String,
      ),
      array(
        'name'   => "params",
        'type'   => VariantVec,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_send_query",
    'desc'   => "pg_send_query() sends a query or queries asynchronously to the connection. Unlike pg_query(), it can send multiple queries at once to PostgreSQL and get the results one by one using pg_get_result().\n\nScript execution is not blocked while the queries are executing. Use pg_connection_busy() to check if the connection is busy (i.e. the query is executing). Queries may be cancelled using pg_cancel_query().\n\nAlthough the user can send multiple queries at once, multiple queries cannot be sent over a busy connection. If a query is sent while the connection is busy, it waits until the last query is finished and discards all its results.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "TRUE on success or FALSE on failure.\n\nUse pg_get_result() to determine the query result.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "query",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_set_client_encoding",
    'desc'   => "pg_set_client_encoding() sets the client encoding and returns 0 if success or -1 if error.\n\nPostgreSQL will automatically convert data in the backend database encoding into the frontend encoding.\n\nThe function used to be called pg_setclientencoding().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns 0 on success or -1 on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "encoding",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_set_error_verbosity",
    'desc'   => "Determines the verbosity of messages returned by pg_last_error() and pg_result_error().\n\npg_set_error_verbosity() sets the verbosity mode, returning the connection's previous setting. In PGSQL_ERRORS_TERSE mode, returned messages include severity, primary text, and position only; this will normally fit on a single line. The default mode (PGSQL_ERRORS_DEFAULT) produces messages that include the above plus any detail, hint, or context fields (these may span multiple lines). The PGSQL_ERRORS_VERBOSE mode includes all available fields. Changing the verbosity does not affect the messages available from already-existing result objects, only subsequently-created ones.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "The previous verbosity level: PGSQL_ERRORS_TERSE, PGSQL_ERRORS_DEFAULT or PGSQL_ERRORS_VERBOSE.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "verbosity",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_trace",
    'desc'   => "pg_trace() enables tracing of the PostgreSQL frontend/backend communication to a file. To fully understand the results, one needs to be familiar with the internals of PostgreSQL communication protocol.\n\nFor those who are not, it can still be useful for tracing errors in queries sent to the server, you could do for example grep '^To backend' trace.log and see what queries actually were sent to the PostgreSQL server. For more information, refer to the » PostgreSQL Documentation.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Boolean,
      'desc'   => "Returns TRUE on success or FALSE on failure.",
    ),
    'args'   => array(
      array(
        'name'   => "pathname",
        'type'   => String,
      ),
      array(
        'name'   => "mode",
        'type'   => String,
        'value'  => "\"w\"",
      ),
      array(
        'name'   => "connection",
        'type'   => Variant,
        'value'  => "null",
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_transaction_status",
    'desc'   => "Returns the current in-transaction status of the server. Caution\n\npg_transaction_status() will give incorrect results when using a PostgreSQL 7.3 server that has the parameter autocommit set to off. The server-side autocommit feature has been deprecated and does not exist in later server versions.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Int32,
      'desc'   => "PGSQL_TRANSACTION_IDLE (currently idle), PGSQL_TRANSACTION_ACTIVE (a command is in progress), PGSQL_TRANSACTION_INTRANS (idle, in a valid transaction block), or PGSQL_TRANSACTION_INERROR (idle, in a failed transaction block). PGSQL_TRANSACTION_UNKNOWN is reported if the connection is bad. PGSQL_TRANSACTION_ACTIVE is reported only when a query has been sent to the server and not yet completed.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_tty",
    'desc'   => "pg_tty() returns the TTY name that server side debugging output is sent to on the given PostgreSQL connection resource.\n\npg_tty() is obsolete, since the server no longer pays attention to the TTY setting, but the function remains for backwards compatibility.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the debug TTY of the connection, or FALSE on error.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_unescape_bytea",
    'desc'   => "pg_unescape_bytea() unescapes PostgreSQL bytea data values. It returns the unescaped string, possibly containing binary data.\n\nWhen you SELECT a bytea type, PostgreSQL returns octal byte values prefixed with '\\' (e.g. \\032). Users are supposed to convert back to binary format manually.\n\nThis function requires PostgreSQL 7.2 or later. With PostgreSQL 7.2.0 and 7.2.1, bytea values must be cast when you enable multi-byte support. i.e. INSERT INTO test_table (image) VALUES ('\$image_escaped'::bytea); PostgreSQL 7.2.2 or later does not need a cast. The exception is when the client and backend character encoding does not match, and there may be multi-byte stream error. User must then cast to bytea to avoid this error.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => String,
      'desc'   => "A string containing the unescaped data.",
    ),
    'args'   => array(
      array(
        'name'   => "data",
        'type'   => String,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_untrace",
    'desc'   => "Stop tracing started by pg_trace().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Boolean,
      'desc'   => "Always returns TRUE.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_update",
    'desc'   => "pg_update() updates records that matches condition with data. If options is specified, pg_convert() is applied to data with specified options. WarningThis function is EXPERIMENTAL. The behaviour of this function, its name, and surrounding documentation may change without notice in a future release of PHP. This function should be used at your own risk.",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns TRUE on success or FALSE on failure. Returns string if PGSQL_DML_STRING is passed via options.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
      array(
        'name'   => "table_name",
        'type'   => String,
      ),
      array(
        'name'   => "data",
        'type'   => Variant,
      ),
      array(
        'name'   => "condition",
        'type'   => Variant,
      ),
      array(
        'name'   => "options",
        'type'   => Int32,
      ),
    ),
  ));

DefineFunction(
  array(
    'name'   => "pg_version",
    'desc'   => "pg_version() returns an array with the client, protocol and server version. Protocol and server versions are only available if PHP was compiled with PostgreSQL 7.4 or later.\n\nFor more detailed server information, use pg_parameter_status().",
    'flags'  =>  HasDocComment,
    'return' => array(
      'type'   => Variant,
      'desc'   => "Returns an array with client, protocol and server keys and values (if available). Returns FALSE on error or invalid connection.",
    ),
    'args'   => array(
      array(
        'name'   => "connection",
        'type'   => Variant,
      ),
    ),
  ));


///////////////////////////////////////////////////////////////////////////////
// Classes
//
// BeginClass
// array (
//   'name'   => name of the class
//   'desc'   => description of the class's purpose
//   'flags'  => attributes of the class, see base.php for possible values
//   'note'   => additional note about this class's schema
//   'parent' => parent class name, if any
//   'ifaces' => array of interfaces tihs class implements
//   'bases'  => extra internal and special base classes this class requires
//   'footer' => extra C++ inserted at end of class declaration
// )
//
// DefineConstant(..)
// DefineConstant(..)
// ...
// DefineFunction(..)
// DefineFunction(..)
// ...
// DefineProperty
// DefineProperty
//
// array (
//   'name'  => name of the property
//   'type'  => type of the property
//   'flags' => attributes of the property
//   'desc'  => description of the property
//   'note'  => additional note about this property's schema
// )
//
// EndClass()

